import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { getalltasks } from './registry'
import { taskroot } from './runner'
import { TASK_GROUPS } from './types'
import type { TaskDef } from './types'

const DOCS_PATH = path.join(taskroot(), 'docs', 'tasks.md')

function escmd(value: string): string {
  return value.replace(/\|/g, '\\|')
}

function envcell(task: TaskDef): string {
  if (!task.env || Object.keys(task.env).length === 0) {
    return '—'
  }
  return Object.entries(task.env)
    .map(([key, val]) => `\`${key}=${val}\``)
    .join(', ')
}

function depscell(task: TaskDef): string {
  if (!task.deps || task.deps.length === 0) {
    return '—'
  }
  return task.deps.map((dep) => `\`${dep}\``).join(', ')
}

function tagscell(task: TaskDef): string {
  if (!task.tags || task.tags.length === 0) {
    return '—'
  }
  return task.tags.map((tag) => `\`${tag}\``).join(', ')
}

function rendertable(tasks: TaskDef[]): string {
  if (tasks.length === 0) {
    return '_No tasks._\n'
  }
  const lines = [
    '| Task | Description | Tags | Deps | Env |',
    '|------|-------------|------|------|-----|',
  ]
  for (const task of tasks) {
    lines.push(
      `| \`yarn task run ${escmd(task.id)}\` | ${escmd(task.description)} | ${tagscell(task)} | ${depscell(task)} | ${envcell(task)} |`,
    )
  }
  return `${lines.join('\n')}\n`
}

export function rendertasksdoc(): string {
  const all = getalltasks()
  const bygroup = new Map<string, TaskDef[]>()
  for (const group of TASK_GROUPS) {
    bygroup.set(group, [])
  }
  for (const task of all) {
    const list = bygroup.get(task.group) ?? []
    list.push(task)
    bygroup.set(task.group, list)
  }

  const parts = [
    '# Task index',
    '',
    'Generated by `yarn task docs`. Do not edit by hand.',
    '',
    'Run any task:',
    '',
    '```bash',
    'yarn task list',
    'yarn task run <task-id>',
    'yarn task explain <task-id>',
    '```',
    '',
    'Nested shorthand: `yarn task <group> <segment> …` (e.g. `yarn task app dev`).',
    '',
  ]

  for (const group of TASK_GROUPS) {
    const tasks = (bygroup.get(group) ?? []).sort((a, b) =>
      a.id.localeCompare(b.id),
    )
    if (tasks.length === 0) {
      continue
    }
    parts.push(`## ${group}`, '', rendertable(tasks), '')
  }

  return `${parts.join('\n').trimEnd()}\n`
}

export function writetasksdoc(): void {
  writeFileSync(DOCS_PATH, rendertasksdoc(), 'utf8')
}

export function checktasksdoc(): boolean {
  const expected = rendertasksdoc()
  let current = ''
  try {
    current = readFileSync(DOCS_PATH, 'utf8')
  } catch {
    return false
  }
  return current === expected
}

export function taskdocpath(): string {
  return DOCS_PATH
}
