/**
 * Color name → constant mapping. Separate from color.ts to avoid circular deps
 * (color → reader → color) that break bundling.
 */
export const colorconsts = {
  black: 'BLACK',
  dkblue: 'DKBLUE',
  dkgreen: 'DKGREEN',
  dkcyan: 'DKCYAN',
  dkred: 'DKRED',
  dkpurple: 'DKPURPLE',
  dkyellow: 'DKYELLOW',
  ltgray: 'LTGRAY',
  dkgray: 'DKGRAY',
  blue: 'BLUE',
  green: 'GREEN',
  cyan: 'CYAN',
  red: 'RED',
  purple: 'PURPLE',
  yellow: 'YELLOW',
  white: 'WHITE',
  brown: 'DKYELLOW',
  dkwhite: 'LTGRAY',
  ltgrey: 'LTGRAY',
  gray: 'LTGRAY',
  grey: 'LTGRAY',
  dkgrey: 'DKGRAY',
  ltblack: 'DKGRAY',
  onblack: 'ONBLACK',
  ondkblue: 'ONDKBLUE',
  ondkgreen: 'ONDKGREEN',
  ondkcyan: 'ONDKCYAN',
  ondkred: 'ONDKRED',
  ondkpurple: 'ONDKPURPLE',
  ondkyellow: 'ONDKYELLOW',
  onltgray: 'ONLTGRAY',
  ondkgray: 'ONDKGRAY',
  onblue: 'ONBLUE',
  ongreen: 'ONGREEN',
  oncyan: 'ONCYAN',
  onred: 'ONRED',
  onpurple: 'ONPURPLE',
  onyellow: 'ONYELLOW',
  onwhite: 'ONWHITE',
  onbrown: 'ONDKYELLOW',
  ondkwhite: 'ONLTGRAY',
  onltgrey: 'ONLTGRAY',
  ongray: 'ONLTGRAY',
  ongrey: 'ONLTGRAY',
  ondkgrey: 'ONDKGRAY',
  onltblack: 'ONDKGRAY',
  onclear: 'ONCLEAR',
  blblack: 'BLBLACK',
  bldkblue: 'BLDKBLUE',
  bldkgreen: 'BLDKGREEN',
  bldkcyan: 'BLDKCYAN',
  bldkred: 'BLDKRED',
  bldkpurple: 'BLDKPURPLE',
  bldkyellow: 'BLDKYELLOW',
  blltgray: 'BLLTGRAY',
  bldkgray: 'BLDKGRAY',
  blblue: 'BLBLUE',
  blgreen: 'BLGREEN',
  blcyan: 'BLCYAN',
  blred: 'BLRED',
  blpurple: 'BLPURPLE',
  blyellow: 'BLYELLOW',
  blwhite: 'BLWHITE',
  blbrown: 'BLDKYELLOW',
  bldkwhite: 'BLLTGRAY',
  blltgrey: 'BLLTGRAY',
  blgray: 'BLLTGRAY',
  blgrey: 'BLLTGRAY',
  bldkgrey: 'BLDKGRAY',
  blltblack: 'BLDKGRAY',
} as const

export type STR_COLOR_TYPE = typeof colorconsts
export type STR_COLOR_KEYS = keyof STR_COLOR_TYPE
export type STR_COLOR_CONST = STR_COLOR_TYPE[STR_COLOR_KEYS]
