'use strict'

const { spawn } = require('node:child_process')
const fs = require('node:fs')
const path = require('node:path')
const {
  AUTH_PORT,
  PATH_NAME,
  RTSP_PORT,
  WHIP_PORT,
  YOUTUBE_RTMPS_BASE,
} = require('./constants.cjs')

let child
let loglines = []
let apppath = ''
let userdata = ''
let packaged = false

function setpaths(opts) {
  apppath = opts.apppath
  userdata = opts.userdata
  packaged = Boolean(opts.packaged)
}

function pushlog(line) {
  const text = String(line).trimEnd()
  if (!text) {
    return
  }
  loglines.push(text)
  if (loglines.length > 200) {
    loglines = loglines.slice(-200)
  }
}

function getlogs() {
  return loglines.slice()
}

function clearlogs() {
  loglines = []
}

function resourcebin(name) {
  if (packaged) {
    return path.join(process.resourcesPath, 'bin', name)
  }
  const plat = `${process.platform === 'darwin' ? 'darwin' : process.platform === 'win32' ? 'win32' : process.platform}-${process.arch === 'arm64' ? 'arm64' : 'x64'}`
  return path.join(apppath, 'vendor', plat, name)
}

function mediamtxbin() {
  const name = process.platform === 'win32' ? 'mediamtx.exe' : 'mediamtx'
  return resourcebin(name)
}

function ffmpegbin() {
  const name = process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg'
  return resourcebin(name)
}

function writeconfig({ certpaths, youtubeStreamKey }) {
  const ffmpeg = ffmpegbin().replace(/\\/g, '/')
  const key = String(youtubeStreamKey || '').trim()
  const rtmpurl = `${YOUTUBE_RTMPS_BASE}/${key}`
  const run =
    `"${ffmpeg}" -hide_banner -loglevel warning -rtsp_transport tcp -i rtsp://127.0.0.1:${RTSP_PORT}/${PATH_NAME} -c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 48000 -f flv "${rtmpurl}"`

  const yaml = `###############################################
# Generated by Zed Cafe YouTube Relay - do not edit by hand
###############################################

logLevel: info
logDestinations: [stdout]

api: no
metrics: no
pprof: no

rtsp: yes
rtspAddress: 127.0.0.1:${RTSP_PORT}
rtmp: no
hls: no
srt: no

webrtc: yes
webrtcAddress: 127.0.0.1:${WHIP_PORT}
webrtcEncryption: true
webrtcServerKey: ${JSON.stringify(certpaths.key)}
webrtcServerCert: ${JSON.stringify(certpaths.cert)}
webrtcAllowOrigins: ['*']
webrtcLocalUDPAddress: 127.0.0.1:8189
webrtcLocalTCPAddress: 127.0.0.1:8189

authMethod: http
authHTTPAddress: http://127.0.0.1:${AUTH_PORT}/auth

paths:
  ${PATH_NAME}:
    runOnReady: ${run}
    runOnReadyRestart: no
`

  const datadir = path.join(userdata, 'mediamtx')
  fs.mkdirSync(datadir, { recursive: true })
  const configpath = path.join(datadir, 'mediamtx.yml')
  fs.writeFileSync(configpath, yaml, 'utf8')
  return { configpath, datadir }
}

function isrunning() {
  return Boolean(child && child.exitCode === null)
}

async function start({ certpaths, youtubeStreamKey }) {
  if (isrunning()) {
    return
  }
  clearlogs()
  const mtx = mediamtxbin()
  const ff = ffmpegbin()
  if (!fs.existsSync(mtx)) {
    throw new Error(`MediaMTX binary missing: ${mtx}. Run fetch-binaries / rebuild.`)
  }
  if (!fs.existsSync(ff)) {
    throw new Error(`ffmpeg binary missing: ${ff}. Run fetch-binaries / rebuild.`)
  }
  if (!String(youtubeStreamKey || '').trim()) {
    throw new Error('YouTube stream key is required in Settings before Start.')
  }

  const { configpath, datadir } = writeconfig({
    certpaths,
    youtubeStreamKey,
  })
  pushlog(`starting mediamtx with ${configpath}`)

  child = spawn(mtx, [configpath], {
    cwd: datadir,
    env: { ...process.env },
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  child.stdout.on('data', (buf) => pushlog(buf.toString('utf8')))
  child.stderr.on('data', (buf) => pushlog(buf.toString('utf8')))
  child.on('exit', (code, signal) => {
    pushlog(`mediamtx exited code=${code} signal=${signal}`)
    child = undefined
  })
}

async function stop() {
  if (!child) {
    return
  }
  const proc = child
  child = undefined
  return new Promise((resolve) => {
    const timer = setTimeout(() => {
      try {
        proc.kill('SIGKILL')
      } catch {
        /* ignore */
      }
      resolve()
    }, 4000)
    proc.once('exit', () => {
      clearTimeout(timer)
      resolve()
    })
    try {
      proc.kill('SIGINT')
    } catch {
      clearTimeout(timer)
      resolve()
    }
  })
}

module.exports = {
  setpaths,
  start,
  stop,
  isrunning,
  getlogs,
  mediamtxbin,
  ffmpegbin,
}
