import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs'
import path from 'node:path'

import { CAFE_PUBLIC_ZEDCAFE_WASM } from 'ops/lib/cafepublicpaths'
import {
  WANIX_FIXTURES_DIR,
  WANIX_PUBLIC_FIXTURES_DIR,
} from 'ops/lib/fixturepaths'
import { requirewanixzedcafedirtyforward } from 'ops/lib/wanix/wanixsubmodule'

const ZEDCAFE_PACKAGE = path.join(WANIX_FIXTURES_DIR, 'zedcafe', 'main.go')
const ZEDCAFE_STAGING_WASM = path.join(
  WANIX_PUBLIC_FIXTURES_DIR,
  'zedcafe.wasm',
)
const ZEDCAFE_PUBLIC_WASM = CAFE_PUBLIC_ZEDCAFE_WASM
const ZEDCAFE_WASM_VERSION_TS = path.join(
  process.cwd(),
  'zss/feature/wanix/wanixzedcafewasmversion.ts',
)

const GOJS_ENV = { ...process.env, GOOS: 'js', GOARCH: 'wasm' }

function writewasmversion(outfile: string) {
  const bytes = readFileSync(outfile)
  const buildid = createHash('sha256').update(bytes).digest('hex').slice(0, 12)
  writeFileSync(
    ZEDCAFE_WASM_VERSION_TS,
    [
      '// Generated by ops/lib/wanix/buildzedcafe.ts — do not edit.',
      `export const WANIX_ZEDCAFE_WASM_BUILD_ID = '${buildid}'`,
      '',
    ].join('\n'),
  )
  process.stdout.write(`zedcafe wasm build id: ${buildid}\n`)
}

function requirego(): void {
  try {
    execFileSync('go', ['version'], { stdio: 'ignore' })
  } catch {
    throw new Error(
      'go not found — install Go (brew install go) to build wanix wasm binaries',
    )
  }
}

function requiregomod(): void {
  const gomod = path.join(WANIX_FIXTURES_DIR, 'go.mod')
  if (!existsSync(gomod)) {
    throw new Error(`missing ${gomod}`)
  }
}

function buildgojspackage(label: string, pkg: string, outfile: string): void {
  process.stdout.write(`go build ${label} -> ${path.basename(outfile)}\n`)
  execFileSync('go', ['build', '-o', outfile, pkg], {
    cwd: WANIX_FIXTURES_DIR,
    stdio: 'inherit',
    env: GOJS_ENV,
  })
}

/**
 * Build zed-cafe export daemon (Go js/wasm) into ops/public/wanix/ and copy to
 * cafe/public/wanix/.
 */
export function buildwanixzedcafe(): void {
  requirego()
  requiregomod()
  requirewanixzedcafedirtyforward()

  if (!existsSync(ZEDCAFE_PACKAGE)) {
    throw new Error(`missing ${ZEDCAFE_PACKAGE}`)
  }

  mkdirSync(WANIX_PUBLIC_FIXTURES_DIR, { recursive: true })
  mkdirSync(path.dirname(ZEDCAFE_PUBLIC_WASM), { recursive: true })

  buildgojspackage('zedcafe', './zedcafe', ZEDCAFE_STAGING_WASM)
  copyFileSync(ZEDCAFE_STAGING_WASM, ZEDCAFE_PUBLIC_WASM)
  writewasmversion(ZEDCAFE_PUBLIC_WASM)
  process.stdout.write(
    `zedcafe.wasm written to ${ZEDCAFE_STAGING_WASM} (copied to ${ZEDCAFE_PUBLIC_WASM})\n`,
  )
}
