name: on merge main

on:
  push:
    branches:
      - main

jobs:
  autoversion:
    name: update version on main and deploy to gh pages
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version-file: .nvmrc

      - name: log version
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: log version
        run: cat ./package.json

      - name: signal result
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

      - name: setup and build
        run: |
          yarn build
          yarn build:copy-cname
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: public # The branch name where you want to push the assets
          FOLDER: ./zss/terminal/dist # The directory where your assets are generated
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          
