name: PR Check - Lint & Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint-and-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: run lint
        run: yarn lint

      - name: check markdown relative links
        run: yarn docs:links

      - name: run tests
        run: yarn test

  e2e:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: install Playwright browsers
        run: npx playwright install --with-deps chromium firefox webkit

      - name: run e2e tests
        run: yarn test:e2e
