name: On PR Merged

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  merge-main-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: emiliopedrollo/auto-merge@v1.2.0
        with:
          github_token: ${{ github.token }}
          target_branch: 'dev'
          commit_message: 'Branch {target_branch} auto-merged {source_ref}'

  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'inc version'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
