name: On PR Merged

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  merge-main-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: emiliopedrollo/auto-merge@v1.2.0
        with:
          github_token: ${{ github.token }}
          target_branch: 'dev'
          commit_message: 'ci: {target_branch} auto-merged {source_ref}'
