name: Push Main - Publish to GH Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          set-safe-directory: true
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: setup and build
        run: |
          yarn
          yarn task run cafe:build
          yarn task run ops:ci:pages:copy-404
          yarn task run ops:ci:pages:copy-cname

      - name: Push
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cafe/dist
          publish_branch: public
          commit_message: 'Build: {sha} {msg}'
