name: update zss version

on:
  workflow_dispatch

jobs:
  autoversion:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: update zss version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          major_pattern: "release:"
          minor_pattern: "/(feat|feature):/"
          bump_each_commit: true
          bump_each_commit_patch_pattern: "/(fix|add):/"
