name: update zss version

on:
  workflow_dispatch

jobs:
  autoversion:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: update zss version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_prefix: 'v'
          major-wording: 'release:'
          minor-wording: 'feat:,feature:'
          patch-wording: 'fix:,add:' 

