name: update zss version

on:
  workflow_dispatch

jobs:
  autoversion:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: scan commits for versioning
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          minor_pattern: "feat: "
          major_pattern: "release: "
          bump_each_commit_patch_pattern: "(fix|add): "
          bump_each_commit: true

      - name: update zss version
        run: |
          echo "test ${{ steps.version.outputs.version }}"
      
      # - name: update zss version
      #   uses: reedyuk/npm-version@1.1.1
      #   with:
      #     version: ${{ steps.version.outputs. }}

      - name: log package after
        run: cat ./package.json
