name: update zss version

on:
  workflow_dispatch

jobs:
  autoversion:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: log package before
        run: cat ./package.json

      - name: scan commits for versioning
        id: version
        uses: paulhatch/semantic-version@5.4.0
        with:
          minor_pattern: "feat: "
          major_pattern: "release: "
          bump_each_commit: true
          bump_each_commit_patch_pattern: "(fix|add): "

      - name: log package after
        run: cat ./package.json
